services:
  app:
    image: ghcr.io/k2ata2/knihovna:latest
    restart: unless-stopped
    networks:
      - proxy
    labels:
      caddy: http://knihovna.k2ata.cz
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  proxy:
    external: true
